<a href="https://colab.research.google.com/github/uzairsiddiqui0899/Python-learning/blob/main/Python_Libraries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [3]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [4]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print(np.full((2,3), 5))

[[5 5 5]
 [5 5 5]]


In [7]:
print(np.arange(0, 10, 2))

[0 2 4 6 8]


In [8]:
print(np.linspace(0, 1, 5))

[0.   0.25 0.5  0.75 1.  ]


In [9]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
np.array([1, 2, 3], dtype=float)

array([1., 2., 3.])

In [12]:
arr = np.array([1.5, 2.7, 3.9])
print(arr.astype(int))

[1 2 3]


In [15]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print(arr[0, 1]) #20 (row 0, col 1)
print(arr[2, 2]) #90 (row 2, col 2)

20
90


In [16]:
print(arr[-1, -2]) #80 (last row, 2nd last col)

80


In [17]:
print(arr[0:2, 1:3]) # rows 0-1, cols 1-2

[[20 30]
 [50 60]]


In [19]:
slice_arr = arr[0, :2]
print(slice_arr)

[10 20]


In [21]:
# Simulate 100k coin flips
# this program will give different probability everytime
rng = np.random.default_rng()
flips = rng.integers(0, 2, size=100000) # 0=tails, 1=heads
prob_heads = np.mean(flips)
print("Estimated probability of heads:", prob_heads)

Estimated probability of heads: 0.49768


In [23]:
# seed command will give same response
rng = np.random.default_rng(seed=2)
flips = rng.integers(0, 2, size=100000) # 0=tails, 1=heads
prob_heads = np.mean(flips)
print("Estimated probability of heads:", prob_heads)

Estimated probability of heads: 0.50012


# Pandas

In [2]:
import pandas as pd

# Create a series
s = pd.Series([10, 20, 20, 30, 40], index = ['a', 'b', 'c', 'd', 'e'])
print(s)

a    10
b    20
c    20
d    30
e    40
dtype: int64


In [3]:
print("Values:", s.values)
print("Indices:", s.index)
print("Dtype:", s.dtype)

Values: [10 20 20 30 40]
Indices: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
Dtype: int64


In [4]:
print(s.head) #useful for very large datasets

<bound method NDFrame.head of a    10
b    20
c    20
d    30
e    40
dtype: int64>


In [5]:
print(s.tail) #useful for very large datasets

<bound method NDFrame.tail of a    10
b    20
c    20
d    30
e    40
dtype: int64>


In [6]:
print(s.value_counts())

20    2
10    1
30    1
40    1
Name: count, dtype: int64


### DataFrame

In [8]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   40        Chicago


In [7]:
from google.colab import files

print("Please upload the 'retail_sales.csv' file from your local machine:")
uploaded = files.upload()

# Assuming the user uploads a file named 'retail_sales.csv'
# If the uploaded file has a different name, please update the next cell manually.

Please upload the 'retail_sales.csv' file from your local machine:


Saving retail_sales.csv to retail_sales.csv


In [8]:
#Load samples CSV
df = pd.read_csv('retail_sales.csv')

#Inspect DataFrame
print("Info:\n", df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Date      1825 non-null   object 
 1   Category  1821 non-null   object 
 2   Sales     1823 non-null   float64
 3   Quantity  1820 non-null   float64
 4   Profit    1825 non-null   float64
 5   Region    1820 non-null   object 
dtypes: float64(3), object(3)
memory usage: 85.7+ KB
Info:
 None


In [7]:
print("\nShape:\n", df.shape)
print("\nData Types:\n", df.dtypes)


Shape:
 (1825, 6)

Data Types:
 Date        datetime64[ns]
Category          category
Sales              float64
Quantity           float64
Profit             float64
Region            category
dtype: object


In [8]:
print("\nStatistical Summary:\n",df.describe())


Statistical Summary:
                                 Date        Sales     Quantity       Profit
count                           1825  1823.000000  1820.000000  1825.000000
mean   2023-07-02 00:00:00.000000256   980.482677    10.053846   248.696130
min              2023-01-01 00:00:00     0.000000     0.000000     0.000000
25%              2023-04-02 00:00:00   784.071354     5.000000   156.916498
50%              2023-07-02 00:00:00   997.725134    10.000000   229.344557
75%              2023-10-01 00:00:00  1208.512721    15.000000   324.867847
max              2023-12-31 00:00:00  1888.932537    19.000000   703.228418
std                              NaN   336.756618     5.515370   118.159627


In [18]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago'],
        'Salary': [50000, 60000, 70000, 80000]}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

Original DataFrame:
       Name  Age           City  Salary
0    Alice   25       New York   50000
1      Bob   30  San Francisco   60000
2  Charlie   35    Los Angeles   70000
3    David   40        Chicago   80000


1. Label based Selection (.Loc)

In [19]:
subset_loc = df.loc[1:3, ['Name', 'Salary']] #all 1,2,3 are included
print("Subset with .loc:\n", subset_loc )

Subset with .loc:
       Name  Salary
1      Bob   60000
2  Charlie   70000
3    David   80000


2. Integer Based Selection (.iloc)

In [20]:
subset_iloc = df.iloc[0:2, 1:3] # 2,3 are not included
print("Subset with .iloc:\n", subset_iloc)

Subset with .iloc:
    Age           City
0   25       New York
1   30  San Francisco


3. Boolean filtering

In [21]:
high_salary = df[df['Salary'] > 60000]
print("Employees with Salary > 60000:\n", high_salary)

Employees with Salary > 60000:
       Name  Age         City  Salary
2  Charlie   35  Los Angeles   70000
3    David   40      Chicago   80000


4. Safe Assignment using .loc

In [22]:
# not using indices, considering we might tackle large datasets
df.loc[df['Age'] < 30, 'Salary'] = 65000
print("Low Age Salary Change:\n", df.loc[df['Age'] < 30, 'Salary'])

Low Age Salary Change:
 0    65000
Name: Salary, dtype: int64


## Handling Data Types

In [9]:
df = pd.read_csv("retail_sales.csv", parse_dates=["Date"],
                 dtype={"Category": "category"})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category      
 2   Sales     1823 non-null   float64       
 3   Quantity  1820 non-null   float64       
 4   Profit    1825 non-null   float64       
 5   Region    1820 non-null   object        
dtypes: category(1), datetime64[ns](1), float64(3), object(1)
memory usage: 73.6+ KB


In [26]:
# converting text to numeric if read incorrectly
df['Profit'] = pd.to_numeric(df['Profit'])
df['Quantity'] = pd.to_numeric(df['Quantity'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category      
 2   Sales     1823 non-null   float64       
 3   Quantity  1820 non-null   float64       
 4   Profit    1825 non-null   float64       
 5   Region    1820 non-null   object        
dtypes: category(1), datetime64[ns](1), float64(3), object(1)
memory usage: 73.6+ KB


In [12]:
# convert City to Category (to reduce memory requirements)
df['Region'] = df['Region'].astype('category')
df.info()
print(df['Region'].memory_usage(deep=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category      
 2   Sales     1823 non-null   float64       
 3   Quantity  1820 non-null   float64       
 4   Profit    1825 non-null   float64       
 5   Region    1820 non-null   category      
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB
2395


### Handling Missing Data

In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={"Category": "category",
           "Region" : "category"}
    )
df.head()

,Date,Category,Sales,Quantity,Profit,Region
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East


In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1821 non-null   category      
 2   Sales     1823 non-null   float64       
 3   Quantity  1820 non-null   float64       
 4   Profit    1825 non-null   float64       
 5   Region    1820 non-null   category      
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB


In [15]:
# Detect missing values
print(df.isna().sum())

Date        0
Category    4
Sales       2
Quantity    5
Profit      0
Region      5
dtype: int64


In [21]:
# Fill missing values with mean
df['Quantity'] = pd.to_numeric(df['Quantity'])
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [18]:
# Fill missing vales with median
df['Sales'] = df['Sales'].fillna(df['Sales'].median())

In [19]:
# Fill missing values with mode
df['Category'] = df['Category'].fillna(df['Category'].mode()[0])

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1825 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      1825 non-null   datetime64[ns]
 1   Category  1825 non-null   category      
 2   Sales     1825 non-null   float64       
 3   Quantity  1825 non-null   float64       
 4   Profit    1825 non-null   float64       
 5   Region    1820 non-null   category      
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 61.3 KB


In [23]:
df.isna().sum()

,0
Date,0
Category,0
Sales,0
Quantity,0
Profit,0
Region,5


In [24]:
df.dropna(subset=['Region'],inplace=True)
df.isna().sum()

,0
Date,0
Category,0
Sales,0
Quantity,0
Profit,0
Region,0


In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1820 entries, 0 to 1824
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype         
---  ------    --------------  -----         
 0   Date      1820 non-null   datetime64[ns]
 1   Category  1820 non-null   category      
 2   Sales     1820 non-null   float64       
 3   Quantity  1820 non-null   float64       
 4   Profit    1820 non-null   float64       
 5   Region    1820 non-null   category      
dtypes: category(2), datetime64[ns](1), float64(3)
memory usage: 75.2 KB


### String Text and Cleaning

In [3]:
import pandas as pd

df = pd.DataFrame({
    'Category': ['Electronics ', 'furniture', 'Home-Appliances', '  electronics', 'FURNITURE']
})

print(df)

          Category
0     Electronics 
1        furniture
2  Home-Appliances
3      electronics
4        FURNITURE


In [4]:
# Strip spaces and convert to Lowercase
df['Category_clean'] = df['Category'].str.strip().str.lower()

print(df)

          Category   Category_clean
0     Electronics       electronics
1        furniture        furniture
2  Home-Appliances  home-appliances
3      electronics      electronics
4        FURNITURE        furniture


In [5]:
# Replace hyphens with space
df['Category_clean'] = df['Category_clean'].str.replace('-', ' ')

print(df)

          Category   Category_clean
0     Electronics       electronics
1        furniture        furniture
2  Home-Appliances  home appliances
3      electronics      electronics
4        FURNITURE        furniture


### Sorting and Ranking

In [9]:
import pandas as pd

df = pd.read_csv(
    "retail_sales.csv",
    parse_dates=["Date"],
    dtype={"Category": "category",
           "Region" : "category"}
    )
df.head()

,Date,Category,Sales,Quantity,Profit,Region
0,2023-01-01,Electronics,1149.014246,11.0,383.664245,North
1,2023-01-01,Clothing,958.520710,7.0,224.054049,East
2,2023-01-01,Home Goods,1473.763845,2.0,466.593090,South
3,2023-01-01,Sports,1230.230419,6.0,123.310460,West
4,2023-01-01,NaN?,828.585950,12.0,88.591355,East


In [10]:
#Sort by Quantity descending and Sales ascending

df_sorted = df.sort_values(by=['Quantity', 'Sales'], ascending=[False, True])
print("Sorted the DataFrame")
df_sorted.head()

Sorted the DataFrame


,Date,Category,Sales,Quantity,Profit,Region
312,2023-03-04,Home Goods,0.000000,19.0,0.000000,West
528,2023-04-16,Sports,0.000000,19.0,270.577388,West
1708,2023-12-08,Sports,227.942727,19.0,61.534381,North
571,2023-04-25,Clothing,361.006937,19.0,57.285585,West
1213,2023-08-31,Sports,368.305917,19.0,73.419555,West


In [12]:
# Rank Sales within Quantity groups
df['Sales_rank'] = df.groupby('Quantity')['Sales'].rank(method='dense', ascending=False)
print("\nSales Rank within Quantity groups: \n", df)


Sales Rank within Quantity groups: 
            Date     Category        Sales  Quantity      Profit Region  \
0    2023-01-01  Electronics  1149.014246      11.0  383.664245  North   
1    2023-01-01     Clothing   958.520710       7.0  224.054049   East   
2    2023-01-01   Home Goods  1473.763845       2.0  466.593090  South   
3    2023-01-01       Sports  1230.230419       6.0  123.310460   West   
4    2023-01-01         NaN?   828.585950      12.0   88.591355   East   
...         ...          ...          ...       ...         ...    ...   
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West   
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North   
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South   
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North   
1824 2023-12-31        Books   703.973443      14.0  134.106006   East   

      Sales_rank  
0           29.0  
1           56.0  
2            7.0

### Merging & Joining

In [13]:
import pandas as pd

#Sample DataFrames
customers = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

orders = pd.DataFrame({
    'OrderID': [101, 102, 103, 104],
    'CustomerID': [1,2,2,3],
    'Amount': [250, 150, 200, 300]
})

In [14]:
#Inner merge on CustomerID
df_inner =pd.merge(customers, orders, on='CustomerID', how='inner')
print("Inner Merge:\n", df_inner)

Inner Merge:
    CustomerID     Name  OrderID  Amount
0           1    Alice      101     250
1           2      Bob      102     150
2           2      Bob      103     200
3           3  Charlie      104     300


### Apply, map, pipe

In [3]:
from google.colab import files

print("Please upload the file from your local machine:")
uploaded = files.upload()

Please upload the file from your local machine:


Saving ecommerce_sales_analytics_5000.csv to ecommerce_sales_analytics_5000.csv


In [17]:
import pandas as pd

df = pd.read_csv('ecommerce_sales_analytics_5000.csv')
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   order_id          5000 non-null   int64  
 1   order_date        5000 non-null   object 
 2   customer_id       5000 non-null   int64  
 3   product_category  5000 non-null   object 
 4   region            5000 non-null   object 
 5   quantity          5000 non-null   int64  
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object 
 9   delivery_days     5000 non-null   int64  
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB


In [18]:
# map() - Label high-value orders
df["payment_type"] = df["payment_method"].map({
    "Card": "Digital",
    "Wallet": "Digital",
    "COD": "Cash"
})

In [19]:
# Verify
df['payment_type'].unique()

array(['Digital', 'Cash'], dtype=object)

In [21]:
#compare before vs after
df[["payment_method", "payment_type"]].head()

,payment_method,payment_type
0,Wallet,Digital
1,Card,Digital
2,COD,Cash
3,Wallet,Digital
4,Wallet,Digital


In [22]:
# Sanity check
df.groupby("payment_type").size()

,0
payment_type,
Cash,1774
Digital,3226


In [23]:
# apply() - Create revenue category
def revenue_category(row):
  if row["revenue"] > 500:
    return "High"
  elif row["revenue"] >= 200:
    return "Medium"
  else:
    return "Low"

df["revenue_category"] = df.apply(revenue_category, axis=1)

In [24]:
# Verify
df["revenue_category"].value_counts()

,count
revenue_category,
High,3252
Medium,1098
Low,650


In [27]:
#Validate logic manually

df[["revenue", "revenue_category"]].sample(10)

# Revenue > 500 -- High
# Between 200-500 -- Medium
# < 200 -- Low

,revenue,revenue_category
3676,876.36,High
3212,1010.84,High
769,1839.28,High
4834,508.48,High
3741,465.53,Medium
2325,978.43,High
4123,234.92,Medium
4727,431.70,Medium
1130,109.34,Low
4037,469.81,Medium


In [28]:
#pipe() - Method chaining
def add_profit(data):
  data["profit"] = data["revenue"] * 0.2
  return data

def add_net_revenue(data):
  data["net_revenue"] = data["revenue"] - data["profit"]
  return data

df_pipe = df.pipe(add_profit).pipe(add_net_revenue)

In [29]:
#Verify
df[["revenue", "profit", "net_revenue"]].head() #check new columns

,revenue,profit,net_revenue
0,1883.20,376.640,1506.560
1,304.10,60.820,243.280
2,644.35,128.870,515.480
3,2569.90,513.980,2055.920
4,468.56,93.712,374.848


### Descriptive Stats and Data Distribution

In [4]:
import pandas as pd

df = pd.read_csv(
    "ecommerce_sales_analytics_5000.csv",
    parse_dates=["order_date"]
)

In [5]:
df.shape #verify dataset before analysis

(5000, 12)

In [6]:
# Core descriptive statistics
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219


In [8]:
df[["unit_price", "revenue"]].describe() #for revenue values

,unit_price,revenue
count,5000.000000,5000.000000
mean,308.418774,1021.955148
std,169.259369,825.584219
min,15.150000,11.210000
25%,161.895000,354.527500
50%,309.890000,796.650000
75%,455.557500,1515.690000
max,599.960000,4119.330000


In [9]:
# Quantiles
df["revenue"].quantile([0.25, 0.5, 0.75])

,revenue
0.25,354.5275
0.50,796.6500
0.75,1515.6900


In [11]:
#Identifying skewness
df["revenue"].mean(), df["revenue"].median()

(np.float64(1021.955148), 796.65)

In [12]:
df["revenue"].skew() #Positive value -- right skew

np.float64(1.0017064603000962)

In [13]:
df.groupby("product_category")["revenue"].describe()
# Do different product categories behave differently?

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56


In [14]:
df.groupby("product_category")["revenue"].mean() #find highest category

,revenue
product_category,
Beauty,1059.281992
Clothing,1000.608570
Electronics,1029.768835
Home,1013.502497


In [17]:
# Using IQR to Understand spread
Q1 = df["revenue"].quantile(0.25)
Q3 = df["revenue"].quantile(0.75)
IQR = Q3 - Q1
print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)

Q1: 354.5275
Q3: 1515.69
IQR: 1161.1625000000001


In [18]:
(Q3 > Q1) and (IQR > 0) #sanity check

np.True_

### Datetime & Time series data

In [19]:
df =df.set_index("order_date")
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[ns]', name='order_date', length=5000, freq=None)

In [20]:
# Monthly revenue analysis
monthly_revenue = df["revenue"].resample("ME").sum()
monthly_revenue

,revenue
order_date,
2022-01-31,35624.89
2022-02-28,29908.89
2022-03-31,30309.28
2022-04-30,30781.96
2022-05-31,41629.24
...,...
2035-05-31,33393.87
2035-06-30,25205.26
2035-07-31,23944.48


In [21]:
# Trend interpretation (% change)
monthly_revenue.pct_change()

,revenue
order_date,
2022-01-31,NaN
2022-02-28,-0.160450
2022-03-31,0.013387
2022-04-30,0.015595
2022-05-31,0.352391
...,...
2035-05-31,0.201727
2035-06-30,-0.245213
2035-07-31,-0.050021


In [22]:
monthly_revenue.index.is_monotonic_increasing #verify

True

In [23]:
print(monthly_revenue.sum(), df["revenue"].sum()) #check
monthly_revenue.sum() <= df["revenue"].sum() #check

5109775.74 5109775.74


np.True_

### Outlier Removal

In [24]:
#IQR method

Q1 = df["revenue"].quantile(0.25)
Q3 = df["revenue"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers_iqr = df[(df["revenue"] < lower_bound) | (df["revenue"] > upper_bound)]

outliers_iqr.shape #Verification

(67, 11)

In [26]:
outliers_iqr[["revenue", "product_category"]].head() #inspect

,revenue,product_category
order_date,,
2022-02-09,3640.56,Home
2022-03-11,3338.37,Beauty
2022-04-13,3449.50,Clothing
2022-05-07,3472.39,Clothing
2022-06-07,3917.54,Electronics


In [29]:
df = df[(df["revenue"] >= lower_bound) & (df["revenue"] <= upper_bound)]
df.shape

(4933, 11)

In [30]:
# Z-Score method

from scipy.stats import zscore

df = pd.read_csv("ecommerce_sales_analytics_5000.csv")
df["revenue_zscore"] = zscore(df["revenue"])
outliers_zscore = df[df["revenue_zscore"].abs() > 3]

# Z-score shows, how many standard deviations a value is from the mean
# Rule: |Z| > 3 -- outlier

outliers_zscore.shape

(26, 13)

In [31]:
df = df[df["revenue_zscore"].abs() <= 3] #removing outliers
df.shape

(4974, 13)